name: Code Analysis

on: [push, pull_request]

jobs:
  check-config:
    runs-on: ubuntu-latest
    outputs:
      analyze_code: ${{ steps.check.outputs.analyze_code }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read config
        id: check
        run: |
          analyze_code=$(yq e '.analyze_code' .github/config.yml)
          echo "::set-output name=analyze_code::$analyze_code"

  lint:
    if: ${{ fromJson(needs.check-config.outputs.analyze_code) == true }}
    runs-on: ubuntu-latest
    needs: check-config
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint mypy

      - name: Run flake8
        run: |
          flake8 .

      - name: Run pylint
        run: |
          pylint **/*.py

      - name: Run mypy
        run: |
          mypy .
